# Generated by Django 2.2.3 on 2019-08-05 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='headimg/201908/05', verbose_name='用户头像')),
                ('head_file_md5', models.CharField(max_length=128, verbose_name='头像图片的MD5值')),
                ('head_file_type', models.CharField(max_length=32, verbose_name='头像图片的文件类型')),
                ('head_file_size', models.IntegerField(default=0, verbose_name='头像图片的文件类型')),
                ('create_times', models.DateTimeField(auto_now_add=True, null=True, verbose_name='头像上传时间')),
                ('update_times', models.DateTimeField(auto_now=True, null=True, verbose_name='头像更改时间')),
            ],
            options={
                'verbose_name': '头像',
                'verbose_name_plural': '头像',
                'db_table': 'HeadImg',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/201908/05', verbose_name='用户图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='图片上传时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='图片更改时间')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likename', models.CharField(max_length=50, verbose_name='喜好')),
            ],
            options={
                'verbose_name': '喜好',
                'verbose_name_plural': '喜好',
                'db_table': 'Like',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('phone', models.CharField(max_length=50, verbose_name='手机号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('use_time', models.DateTimeField(auto_now_add=True, verbose_name='最近登录时间')),
                ('born_time', models.DateTimeField(auto_now_add=True, verbose_name='出生日期')),
                ('sex', models.BooleanField(blank=True, verbose_name='性别')),
                ('job', models.CharField(max_length=50, verbose_name='职业')),
                ('state_info', models.BooleanField(blank=True, verbose_name='信息是否完善')),
                ('fan', models.ManyToManyField(to='user.Like', verbose_name='喜好')),
                ('img_head', models.ManyToManyField(to='user.HeadImg', verbose_name='头像')),
                ('picture', models.ManyToManyField(to='user.Image', verbose_name='图片')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
            },
        ),
    ]
