# Generated by Django 2.2.3 on 2019-08-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190806_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(default='', max_length=256, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='image',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='图片更改时间'),
        ),
    ]
