# Generated by Django 2.2.3 on 2019-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_image_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(default='', max_length=50, verbose_name='地区'),
        ),
    ]
