# Generated by Django 2.2.3 on 2019-08-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190812_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sample3', to='user.User', verbose_name='第一人称ID')),
                ('third_person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sample4', to='user.User', verbose_name='第三人称ID')),
            ],
        ),
    ]
