# Generated by Django 2.2.3 on 2019-08-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(default='', max_length=50, verbose_name='车标')),
                ('car_type', models.CharField(default='', max_length=50, verbose_name='车型')),
                ('car_color', models.CharField(default='', max_length=50, verbose_name='颜色')),
                ('car_value', models.CharField(default='', max_length=50, verbose_name='估值')),
                ('car_person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户ID')),
            ],
        ),
    ]
