# Generated by Django 2.2.3 on 2019-08-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_carbarn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_licence',
            field=models.CharField(default='', max_length=256, verbose_name='驾驶证'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license',
            field=models.CharField(default='', max_length=256, verbose_name='行驶证'),
        ),
    ]
