# Generated by Django 2.2.3 on 2019-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190813_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign',
            field=models.CharField(default='', max_length=50, verbose_name='星座'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_licence',
            field=models.CharField(default='', max_length=256, verbose_name='行驶证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_license',
            field=models.CharField(default='', max_length=256, verbose_name='驾驶证'),
        ),
    ]
